name = "SpectrumBase"
uuid = "b02fe80f-c43c-4f43-a417-a67622f503c9"
authors = ["Bon Leif Amalla <bonleifamalla@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "Unitful"]
